before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: 'main'
archives:
  - format: zip
    name_template: 's3-hook_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
changelog:
  skip: true