before:
  hooks:
builds:
  - 
    id: s3Hook
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: 'main'
  - 
    id: controlTower
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    dir: ./control_tower
    binary: 'main'
archives:
  - 
    id: s3HookArchive
    builds: [s3Hook]
    format: zip
    name_template: 's3-hook_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - 
    id: controlTowerArchive
    builds: [controlTower]
    format: zip
    name_template: 'controlTower_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
release:
changelog:
  skip: true