env:
  - TAG_VERSION={{ index (split .Version "-") 0 }}
  - TYPE_INTEGRSTION={{ .Version }}
before:
  hooks:
builds:
  -
    id: controlTower
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: 'main'
archives:
  - 
    id: s3HookArchive
    builds: [s3Hook]
    format: zip
    name_template: 's3-hook_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - 
    id: controlTowerArchive
    builds: [controlTower]
    format: zip
    name_template:  >-
      control_tower_{{ .Version }}_{{ .Os }}_{{ .Arch }}__{{ index (split .Version "-") 0 }}__{{ .Env.TYPE_INTEGRSTION  }}
release:
changelog:
  skip: true