env:
  - TAG_VERSION={{ index (split .Version "-") 0 }}
  - TYPE_INTEGRSTION={{ .Version }}
before:
  hooks:
builds:
  -
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: 'main'
    dir: >-
    {{- if eq (index (split .Version "-") 1) "CT" }}./control_tower
    {{- else }}.{{ end }}
      
archives:
  -
    format: zip
    name_template:  >-
      {{ if eq (index (split .Version "-") 1) "CT" }}control_tower{{ else }}s3-hook{{ end }}_{{ index (split .Version "-") 0 }}_{{ .Os }}_{{ .Arch }}
release:
changelog:
  skip: true