name: Upload new release
on:
  release:
    types: [published]

jobs:
  build_function:
    name: Build function
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
  upload_to_buckets:
    name: Upload to S3 buckets
    runs-on: ubuntu-latest
    needs: build_function
    strategy:
      matrix:
        aws_region:
          - 'us-east-1'
  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Receive integraion
        id: integration-receiver
        run: |
          integration=$(echo "${{ github.event.release.tag_name }}" | cut -d- -f2)
          echo '::set-output name=INTEGRATION::${integration}'

      - name: Receive version clean
        id: version-receiver-without
        run: |
         version=$(echo "${{ github.event.release.tag_name }}" | cut -d- -f1)
         version_without = $(echo ${version:1})
         echo '::set-output name=VERSION_CLEAN::${version_without})'
      - name: download zip
        run: |

          if [${{ steps.integration-receiver.outputs.INTEGRATION }} = "CT"]; then
            wget -c https://github.com/resdenia/github-action-workflow/releases/download/${{ github.event.release.tag_name }}/control_tower_${{ steps.version-receiver.outputs.VERSION_CLEAN }}_linux_amd64.zip -O function.zip
          else
            wget -c https://github.com/resdenia/github-action-workflow/releases/download/${{ github.event.release.tag_name }}/s3-hook_${{ steps.version-receiver.outputs.VERSION_CLEAN }}_linux_amd64.zip -O function.zip
          fi
        shell: bash
      - name: create new version
        run: |

          if [${{ steps.integration-receiver.outputs.INTEGRATION }} = "CT"]; then
            cp ./control-tower/sam-template.yaml ./sam-template-${{ matrix.aws_region }}.yaml
          else
            cp ./sam-template.yaml ./sam-template-${{ matrix.aws_region }}.yaml
          fi
          sed -i "s/<<VERSION>>/${{ steps.version-receiver-without.outputs.VERSION_CLEAN }}/" "./sam-template-${{ matrix.aws_region }}.yaml"
          sed -i "s/<<REGION>>/${{ matrix.aws_region }}/" "./sam-template-${{ matrix.aws_region }}.yaml"
        shell: bash
      - name: Upload to aws
        run: |

          sudo apt-get update
          sudo apt-get install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ matrix.aws_region }}
          if [${{ steps.integration-receiver.outputs.INTEGRATION }} = "CT"]; then
          aws s3 cp ./sam-template-${{ matrix.aws_region }}.yaml s3://tmpdata-bucket/s3-hook/control-tower/${{ steps.version-receiver-without.outputs.VERSION_CLEAN }}/sam-template.yaml --acl public-read
            aws s3 cp ./function.zip s3://tmpdata-bucket-${{ matrix.aws_region }}/s3-hook/control-tower/${{ steps.version-receiver-without.outputs.VERSION_CLEAN }}/function.zip --acl public-read
          else
            aws s3 cp ./sam-template-${{ matrix.aws_region }}.yaml s3://tmpdata-bucket}/s3-hook/${{ steps.version-receiver-without.outputs.VERSION_CLEAN }}/sam-template.yaml --acl public-read
            aws s3 cp ./function.zip s3://tmpdata-bucket/s3-hook/${{ steps.version-receiver-without.outputs.VERSION_CLEAN }}/function.zip --acl public-read
          fi
        shell: bash
      - name: Clean
        run: |
          rm ./sam-template-${{ matrix.aws_region }}.yaml
          rm ./function.zip
